echo "To run a specific test file:"
echo "  dotnet test --filter \"FullyQualifiedName~Namespace.Class.\""
echo "  Ex.  dotnet test --filter \"Splunk.Logging.TestTcp.\""
echo""
echo "To run a specific test case:"
echo "  dotnet test --filter \"FullyQualifiedName=Namespace.ClassName.MethodName\""
echo "  Ex.  dotnet test --filter \"Splunk.Logging.TestTcp.TestTcpTraceListener\""
echo""
echo "To see list of discovered tests:"
echo "  dotnet test -t"
